### ISSUE TITLE
Working with subclassed models

### ISSUE THREAD

**Issue by chaithyagr** [andreped/GradientAccumulator#23]
Right now, if we have a model which is subclassed from `tf.keras.Model`, we cannot use this.

Just subclassing from `GAModelWrapper` will not help as we need to call `__init__` for this class after `self.trainable_variables` are used.
Also, we cant have the `__init__` call later after configuring model, as this will cause an error as the underlying  `tf.keras.Model.__init__` needs to be called first!

To prevent this awkward situation, it makes sense to add:
```python

def reinit_grad_accum(self):
    self.gradient_accumulation = [tf.Variable(tf.zeros_like(v, dtype=tf.float32), trainable=False, name="accum_" + str(i)) for i, v in
                                      enumerate(self.trainable_variables)]
```

This function can just be called as desired later by us again to make sure everything works fine.

**Comment by andreped** [comment]
Great idea! If you get a working solution, please make a PR.

Just remember to update the unit tests to check whether it works.

An example of a unit test you want to update is this one:
https://github.com/andreped/GradientAccumulator/blob/main/tests/test_expected_result.py

Here we check that we reach the same results using GA compared to regular batch training.

**Comment by dmus** [comment]
I am having this issue. Could you elaborate on where to call this `reinit_grad_accum`?

**Comment by chaithyagr** [comment]
Hey!
Note that this function is still not implemented in main branch. If you write it yourself, please call it after populating your model in the init function. Make sure that trainable variables are populated with all your model weights

**Comment by dmus** [comment]
I added these lines at the top of the train_step:
       ```
 if self.first_call:
            self.reinit_grad_accum()
            self.first_call = False
```

**Comment by andreped** [comment]
@chaithyagr Just had the time to return to this. I completely misunderstood what the problem was. Yes, then it is quite easy to solve. I added the method you suggested at the top of the thread to the `GAModelWrapper` class. Will update the README regarding this as well.

> I added these lines at the top of the train_step

@dmus Correct me if I'm wrong, but shouldn't it work to reinit right after `model.compile()`. You do not need to do this inside the `train_step`.

**Comment by andreped** [comment]
If any of you had time, it would be great if you could install the latest version from the main branch and verify that it works as expected for you:
```
pip install git+https://github.com/andreped/GradientAccumulator --upgrade --force-reinstall
```

When this is solved, I will make a new release.

**Comment by andreped** [comment]
Fixed in latest release: https://github.com/andreped/GradientAccumulator/releases/tag/v0.3.0
