### ISSUE TITLE
GradientAccumulateOptimizer breaks with TensorFlow 2.11

### ISSUE THREAD

**Issue by Lunariz** [andreped/GradientAccumulator#37]
2.11 has made some changes to how the base optimizer works, as shown in the release notes:

https://github.com/tensorflow/tensorflow/releases

As a result, using the GradientAccumulateOptimizer on this version now gives the following error:

`AttributeError: 'GradientAccumulateOptimizer' object has no attribute '_learning_rate'`

**Comment by Lunariz** [comment]
For anyone running into this, you can use the following workaround:

1. In accumulators.py:111, change `tf.keras.optimizers.Optimizer` to `tf.keras.optimizers.legacy.Optimizer`
2. When passing in another optimizer during construction, use its legacy version, e.g. `tf.keras.optimizers.legacy.Adam` instead of `tf.keras.optimizers.Adam`

**Comment by andreped** [comment]
Hello, @Lunariz.

I have seen the deprecation warning previously, so I'm not surprised this became an issue with the latest release.

I doubt the `tf.keras.optimizers.legacy.Optimizer` exist for older versions of tf2, hence doing (1) is not optimal. Same applies to (2). But I could run a test.

Alternatively, I could check which tf versions that is installed dynamically and then choose the optimizer. However, I believe the behaviour of the optimizer has also changed. Thus, this has to be handled with care.

Will run some tests first and try to find a generic solution that is backward compatible.

**Comment by andreped** [comment]
Just added a test to check if I can reproduce the issue on tf 2.11 here:
https://github.com/andreped/GradientAccumulator/blob/main/.github/workflows/test.yml#L115

However, the current test does not use the optimizer wrapper, only the model wrapper. In this case it worked.
Therefore, for now, I would encourage you to use the model wrapper instead.

The optimizer wrapper is also not as robust. For instance, using dynamic optimizers such as Adam give poorer batch approximation compared to the model wrapper solution.

Is there a specific reason why you chose to use the optimizer wrapper instead, @Lunariz?

**Comment by Lunariz** [comment]
I've downgraded back to tf 2.10 because 2.11+ doesn't support GPU on Windows anymore for some reason. So I'm not concerned about this issue anymore personally!

As for your question - I'm using a custom model that creates multiple optimizers internally.

**Comment by andreped** [comment]
> I've downgraded back to tf 2.10 because 2.11+ doesn't support GPU on Windows anymore for some reason. So I'm not concerned about this issue anymore personally!

OK, no worries. Haven't started using 2.11 yet, but I will keep this issue open until this is solved.

> I'm using a custom model that creates multiple optimizers internally.

OK, interesting. Then I shall try to get the optimizer wrapper working in the near future. Quite preoccupied with wrapping up my PhD work atm. You could make an attempt yourself, if you want.

**Comment by andreped** [comment]
I have now added a fix for it. I added a dynamic method to check which TF version that was in use and based on which chooses the legacy option or not (see [here](https://github.com/andreped/GradientAccumulator/blob/main/gradient_accumulator/accumulators.py#L7)).

Added similar fixes to dynamically choose the right optimizer for the unit tests.

All unit tests seem to pass at least (see [here](https://github.com/andreped/GradientAccumulator/actions/runs/4631818717)).

Will make a new release soon with the fix.
