### ISSUE TITLE
Mixed precision not working as intended with AccumBatchNormalization

### ISSUE THREAD

**Issue by mhoibo** [andreped/GradientAccumulator#73]
**Describe the bug**
Tried to use mixed precision with AccumBatchNormalization training a simple U-Net. Resulted in `TypeError`.

See error message below:

```
TypeError: Exception encountered when calling layer "accum_batch_normalization" "                 f"(type AccumBatchNormalization).

in user code:

    File "/home/username/workspace/project/environment/lib/python3.8/site-packages/gradient_accumulator/layers.py", line 154, in call  *
        mean_scaled = mean / tf.cast(self.accum_steps_tf, self._param_dtype)

    TypeError: `x` and `y` must have the same dtype, got tf.float16 != tf.float32.


Call arguments received by layer "accum_batch_normalization" "                 f"(type AccumBatchNormalization):
  • inputs=tf.Tensor(shape=(None, 1024, 1024, 16), dtype=float16)
  • training=True
  • mask=None
```

It seems like [this unit test](https://github.com/andreped/GradientAccumulator/blob/main/tests/test_mp_batch_norm.py) is never being ran in the CIs, which likely would reproduce this issue.

**Comment by dbouget** [comment]
One trick to try is to force the dtype when calling the layer, worked for me at least.

`x = AccumBatchNormalization(accum_steps=accum_steps, dtype="float32")(x)`

**Comment by andreped** [comment]
I added a unit test for this in 358d213b98434dc7e136a5b2bee2222d12c7d531.

What's strange to me is that I was unable to reproduce this issue. However, I do not have access to a GPU when testing, which may mean that some stuff is still happening on float32, even though I enable mixed precision.

**Comment by andreped** [comment]
@mhoibo When you have time, could you try installing `gradient-accumulator` from source (see instructions [here](https://github.com/andreped/GradientAccumulator#install)). Just remember to uninstall it properly first or add `-U`, just to see if everything now works for you?

**Comment by mhoibo** [comment]
Yeah, I'll try that!

**Comment by mhoibo** [comment]
It worked now, thank you:)

**Comment by andreped** [comment]
Installing latest from source resolved the issue. Could you test that it works for you, @dbouget? If so, I can make a new patch release.

**Comment by andreped** [comment]
New patch release is out which should include this fix:
https://pypi.org/project/gradient-accumulator/0.4.2/

Let me know if it works for you without setting the `dtype="float32"` as arg for the `AccumBatchNormalization` layer.
